### ISSUE TITLE
Error in is_bst()

### ISSUE THREAD

**Issue by kristofmeixner** [dawsonjon/speedometer#1]
Hi!

Just to let you know there is an error in your `is_bst()` method in `gps.c`.

```C
/*Find last Sunday of October*/
for(i=31; i>=1; i--){
  if(day_of_week(year + 2000, 3, i) == 0) break;
 }
```
`3` should be `10` instead for end of BST.

**Comment by dawsonjon** [comment]
Thanks very much for pointing out these errors.
Jon

**Comment by kristofmeixner** [comment]
No problem
